import React, { useEffect, useState } from 'react';
import Icard1 from '../../components/Influencers/Icard1';
import Profile from '../../components/Influencers/Profile';
import Campaign2 from '../../components/standard/Campaign2';
import NumbersSpeak from '../../components/standard/NumbersSpeak';
import Plateforms from '../../components/standard/Plateforms';
import Head from 'next/head';
import { collection, onSnapshot, getDocs } from 'firebase/firestore';
import { db } from '../../firebase';
import { MoonLoader } from 'react-spinners';

// export async function getStaticProps() {
//   let userData = [];

//   const querySnapshot = await getDocs(collection(db, 'influencers'));
//   querySnapshot.forEach((doc) => {
//     userData.push({ ...doc.data(), id: doc.id });
//   });

//   return {
//     props: {
//       userdata: JSON.stringify(userData) || [],
//     },
//     revalidate: 10, // In seconds
//   };
// }

function Influencers() {
  // let influencersData = JSON.parse(userdata);

  const [users, setUsers] = useState([]);
  console.log(users);

  useEffect(() => {
    // setUsers(user);
    try {
      onSnapshot(collection(db, 'influencers'), (snapshot) => {
        let users = [];
        snapshot.docs.forEach((doc) => {
          users.push({ ...doc.data(), id: doc.id });
        });
        setUsers(users);
      });
    } catch (error) {}
  }, []);
  return (
    <div className='relative overflow-hidden xl:mt-20 mt-10'>
      <Head>
        <title>Influencers-Arabiads</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='right-0 hidden xl:inline-grid absolute top-0 [z-index:-1]'>
        <img
          src='/standardimages/servicelinetop.png'
          alt=''
          className='h-screen w-[100vw] '
        />
      </div>
      <div className='max-w-screen-xl mx-auto  '>
        <div className='grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 '>
          {users.length >= 0 &&
            users.map((singleUser) => (
              <div key={singleUser.id} className='flex mx-auto'>
                {' '}
                <Profile user={singleUser} />{' '}
              </div>
            ))}

          {!users.length && (
            <div className='mb-24 h-10 p-24 col-span-2 flex justify-end  '>
              {' '}
              <MoonLoader color={'black'} size='30px' />{' '}
            </div>
          )}
        </div>
        <div className='card-width mt-10'>
          <Icard1 />
        </div>
        <NumbersSpeak />
        <Plateforms />
        <Campaign2 />
      </div>
    </div>
  );
}

export default Influencers;
