import React, { useEffect, useState } from "react";
import Icard1 from "../../components/Influencers/Icard1";
import Profile from "../../components/Influencers/Profile";
import Campaign2 from "../../components/standard/Campaign2";
import NumbersSpeak from "../../components/standard/NumbersSpeak";
import Plateforms from "../../components/standard/Plateforms";
import Head from "next/head";
import { collection, onSnapshot, query, orderBy } from "firebase/firestore";
import { db } from "../../firebase";
import { MoonLoader } from "react-spinners";
import { motion } from "framer-motion";
import AOS from "aos";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common", "home"])),
      locale,
      // Will be passed to the page component as props
    },
  };
}

function Influencers() {
  // let influencersData = JSON.parse(userdata);

  const [users, setUsers] = useState([]);
  console.log(users);
  useEffect(() => {
    // setUsers(user);
    AOS.init({
      // Global settings:
      disable: "mobile", // accepts following values: 'phone', 'tablet', 'mobile', boolean, expression or function
    });
    const q = query(collection(db, "influencers"), orderBy("filter", "desc"));
    // try {
    onSnapshot(q, (snapshot) => {
      let users = [];
      snapshot.docs.forEach((doc) => {
        users.push({ ...doc.data(), id: doc.id });
      });
      setUsers(users);
    });
    // } catch (error) {}
    return () => {
      setUsers([]);
    };
  }, []);
  return (
    <div className='relative  xl:mt-20 mt-10 overflow-hidden xl:overflow-visible'>
      <Head>
        <title>Influencers-Arabiads</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.ico' />
      </Head>
      <div className='right-0 hidden xl:inline-grid absolute xl:top-0 2xl:-top-[4%] [z-index:-1]'>
        <img
          src='/standardimages/servicelinetop.png'
          alt=''
          className=' w-[100vw] object-cover'
        />
      </div>

      {
        <div className='right-0 hidden xl:inline-grid absolute  top-[40%] [z-index:-1]'>
          <img
            src='/standardimages/servicemiddle.png'
            alt=''
            className='scale[1.2] w-[100vw] object-cover'
          />
        </div>
      }
      <div className='right-0 hidden xl:inline-grid absolute  top-[62%] [z-index:-1]'>
        <img
          src='/standardimages/card5line.png'
          alt=''
          className='scale[1.2] w-[100vw] object-cover'
        />
      </div>
      <div className='max-w-screen-xl mx-auto  '>
        <div className='grid grid-cols-1 md:grid-cols-2  lg:grid-cols-3 xl:grid-cols-4 '>
          {users.length >= 0 &&
            users.map((singleUser) => (
              <div
                key={singleUser.id}
                className='flex px-5 md:px-0 xl:mx-auto justify-center'
              >
                {" "}
                <Profile user={singleUser} />{" "}
              </div>
            ))}

          {!users.length && (
            <div className='mb-24 h-10 p-24 col-span-2 flex justify-end  '>
              {" "}
              <MoonLoader color={"black"} size='30px' />{" "}
            </div>
          )}
        </div>
        <div className='right-5 hidden xl:inline-grid absolute top-[5%] [z-index:-1]'>
          <motion.img
            animate={{
              scale: [0.7, 1.2],
              opacity: [0, 0.8, 0],
              // rotate: [0, 0, 270, 270, 0],
            }}
            transition={{ duration: 10, repeat: Infinity }}
            src='/standardimages/pulseblue.png'
            alt=''
            // className='  animate-animate-pulse  '
          />
        </div>
        <div className='left-5 hidden xl:inline-grid absolute top-[30%] [z-index:-1]'>
          <motion.img
            animate={{
              scale: [0.7, 1.2],
              opacity: [0, 0.8, 0],
              // rotate: [0, 0, 270, 270, 0],
            }}
            transition={{ duration: 10, repeat: Infinity }}
            src='/standardimages/pulseorange.png'
            alt=''
            // className='  animate-animate-pulse  '
          />
        </div>
        <div className='card-width mt-20 xl:my-[8rem] '>
          {
            // <img
            //   src='/standardimages/card5line.png'
            //   alt=''
            //   className='hidden absolute w-[100vw] scale-[1.7] 4xl:scale-[2.4] xl:inline-grid top-[35%]  bg-cover '
            // />
          }

          <Icard1 />
        </div>

        <NumbersSpeak />
        <Plateforms />
        <Campaign2 />
      </div>
    </div>
  );
}

export default Influencers;
