import { useEffect, useState } from 'react';
import Scard2 from '../../components/Services/Scard2';
import Campaign2 from '../../components/standard/Campaign2';
import NumbersSpeak from '../../components/standard/NumbersSpeak';
import Plateforms from '../../components/standard/Plateforms';
import Users from '../../components/Talents/Users';
import Head from 'next/head';

function Talents() {
  let [users, setUsers] = useState([]);

  let user = [
    {
      id: 1,
      name: ' Ghazi',
      role: ['Caster'],
      tournaments: [
        'Dota 2 International',
        'Battle of the Gamers by BMW',
        'Insomnia',
        'Ooredoo Nation',
      ],
      instagramLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      facebookLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      twitterLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      twitchLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      youtubeLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      twitter: 'https://twitter.com/gggazyyy',
      liquipediaLink: 'https://www.facebook.com/gaming/KayyaliGaming',

      img: 'https://influencers.ar-ad.com/wp-content/uploads/2022/02/ghazi.png',
    },
    {
      id: 2,
      name: 'k0de2 ',
      role: ['CASTER', 'ANALYST'],
      instagramLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      facebookLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      twitterLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      twitchLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      youtubeLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      liquipediaLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      tournaments: [
        'PMGC Grand Finals 20202021',
        'BLAST PRO GLOBAL FINAL BAHRAIN',
        'PMWL West 2020',
        'GET PUBGM 2021',
      ],
      img: 'https://influencers.ar-ad.com/wp-content/uploads/2021/07/cm-image-2.png',
    },
    {
      id: 3,
      name: 'k0de ',
      role: ['CASTER', 'ANALYST'],

      instagramLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      facebookLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      twitterLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      twitchLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      youtubeLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      liquipediaLink: 'https://www.facebook.com/gaming/KayyaliGaming',
      tournaments: [
        'PMGC Grand Finals 20202021',
        'BLAST PRO GLOBAL FINAL BAHRAIN',
        'PMWL West 2020',
        'GET PUBGM 2021',
      ],
      img: 'https://influencers.ar-ad.com/wp-content/uploads/2021/07/cm-image-2.png',
    },
  ];
  useEffect(() => {
    setUsers(user);
  }, []);
  return (
    <div className='relative overflow-hidden xl:mt-20'>
      <Head>
        <title>Esports Talents-Arabiads</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='right-0 hidden xl:inline-grid absolute top-0 [z-index:-1]'>
        <img
          src='/standardimages/servicelinetop.png'
          alt=''
          className='h-screen w-[100vw] '
        />
      </div>
      <div className='max-w-screen-xl mx-auto  '>
        <Users user={users} />
        <div className='card-width'>
          <Scard2 />
        </div>
        <NumbersSpeak />
        <Plateforms />
        <Campaign2 />
      </div>
    </div>
  );
}

export default Talents;
