import { useEffect, useState } from 'react';
import Scard2 from '../../components/Services/Scard2';
import Campaign2 from '../../components/standard/Campaign2';
import NumbersSpeak from '../../components/standard/NumbersSpeak';
import Plateforms from '../../components/standard/Plateforms';
import Users from '../../components/Talents/Users';
import Head from 'next/head';
import { db } from '../../firebase';
import { motion } from 'framer-motion';

// firebase import
import { collection, onSnapshot, getDocs } from 'firebase/firestore';

function Talents() {
  // let talentsData = JSON.parse(userdata);
  let [users, setUsers] = useState([]);

  useEffect(() => {
    // setUsers(user);
    try {
      onSnapshot(collection(db, 'talents'), (snapshot) => {
        let users = [];
        snapshot.docs.forEach((doc) => {
          users.push({ ...doc.data(), id: doc.id });
        });
        setUsers(users);
      });
    } catch (error) {}
  }, []);
  return (
    <div className='relative  xl:mt-20 '>
      <Head>
        <title>Esports Talents-Arabiads</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='right-0 hidden xl:inline-grid absolute xl:top-0 2xl-top-[7%] [z-index:-1]'>
        <img
          src='/standardimages/servicelinetop.png'
          alt=''
          className='h-screen w-[100vw] '
        />
      </div>
      <div className='right-0  hidden xl:inline-grid absolute top-[25%] [z-index:-1]'>
        <img
          src='/standardimages/servicemiddle.png'
          alt=''
          className='h-screen scale-[1.3] 2xl:scale-[1.3] 3xl:scale-[2] object-cover'
        />
      </div>
      <div className='-right-[5%] 2xl:right-5 2xl:top-[5%] hidden xl:inline-grid absolute top-[10%] [z-index:-1]'>
        <motion.img
          animate={{
            scale: [0.7, 1.2],
            opacity: [0, 0.8, 0],
            // rotate: [0, 0, 270, 270, 0],
          }}
          transition={{ duration: 10, repeat: Infinity }}
          src='/standardimages/pulseblue.png'
          alt=''
          // className='  animate-animate-pulse  '
        />
      </div>
      <div className='max-w-screen-xl mx-auto  '>
        <Users user={users} />

        <div className='card-width'>
          <Scard2 />
        </div>
        <NumbersSpeak />
        <Plateforms />
        <Campaign2 />
      </div>
    </div>
  );
}

export default Talents;
