import Acard1 from "../../components/about/Acard1";
import Acard2 from "../../components/about/Acard2";
import Campaign from "../../components/standard/Campaign";
import NumbersSpeak from "../../components/standard/NumbersSpeak";
import Plateforms from "../../components/standard/Plateforms";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import Head from "next/head";

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common", "home"])),
      locale,
      // Will be passed to the page component as props
    },
  };
}
function About() {
  return (
    <>
      <div className=''>
        <Head>
          <title>About-Arabiads</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/logo.ico' />
        </Head>
        <div className=' hidden absolute  -left-[0%] w-[2650px] h-[200vh]  service-mid bg-no-repeat   xl:inline-grid '></div>
        <div className='left-0 hidden xl:inline-grid absolute xl:top-[45%] 2xl:top-[25%] 4xl:top-[5%] [z-index:-1] '>
          <img
            src='/standardimages/aboutline.png'
            alt=''
            className=' w-[100vw] object-cover'
          />
        </div>
        <div className={`relative overflow-hidden xl:mt-20`}>
          <div className={`max-w-screen-xl mx-auto  `}>
            <Acard1 />
            <Acard2 />

            <NumbersSpeak />
            <Plateforms />
          </div>
          <Campaign />
        </div>
      </div>
    </>
  );
}

export default About;
